package com.example.shopping_list;

import java.util.List;

public class SuggestionsData {

    public static final List<SuggestionProduct> ALL = List.of(

            // ── ירקות ופירות ──
            new SuggestionProduct("עגבניות", "ירקות ופירות"),
            new SuggestionProduct("מלפפונים", "ירקות ופירות"),
            new SuggestionProduct("פלפל אדום", "ירקות ופירות"),
            new SuggestionProduct("פלפל צהוב", "ירקות ופירות"),
            new SuggestionProduct("פלפל ירוק", "ירקות ופירות"),
            new SuggestionProduct("בצל", "ירקות ופירות"),
            new SuggestionProduct("בצל סגול", "ירקות ופירות"),
            new SuggestionProduct("שום", "ירקות ופירות"),
            new SuggestionProduct("גזר", "ירקות ופירות"),
            new SuggestionProduct("תפוח אדמה", "ירקות ופירות"),
            new SuggestionProduct("בטטה", "ירקות ופירות"),
            new SuggestionProduct("קישוא", "ירקות ופירות"),
            new SuggestionProduct("חציל", "ירקות ופירות"),
            new SuggestionProduct("כרובית", "ירקות ופירות"),
            new SuggestionProduct("ברוקולי", "ירקות ופירות"),
            new SuggestionProduct("כרוב", "ירקות ופירות"),
            new SuggestionProduct("חסה", "ירקות ופירות"),
            new SuggestionProduct("תרד", "ירקות ופירות"),
            new SuggestionProduct("פטרוזיליה", "ירקות ופירות"),
            new SuggestionProduct("כוסברה", "ירקות ופירות"),
            new SuggestionProduct("נענע", "ירקות ופירות"),
            new SuggestionProduct("לימון", "ירקות ופירות"),
            new SuggestionProduct("תפוח עץ", "ירקות ופירות"),
            new SuggestionProduct("אבוקדו", "ירקות ופירות"),
            new SuggestionProduct("בננה", "ירקות ופירות"),
            new SuggestionProduct("תות שדה", "ירקות ופירות"),
            new SuggestionProduct("ענבים", "ירקות ופירות"),
            new SuggestionProduct("אבטיח", "ירקות ופירות"),
            new SuggestionProduct("מלון", "ירקות ופירות"),
            new SuggestionProduct("מנגו", "ירקות ופירות"),
            new SuggestionProduct("אנanas", "ירקות ופירות"),
            new SuggestionProduct("פטל", "ירקות ופירות"),
            new SuggestionProduct("אוכמניות", "ירקות ופירות"),
            new SuggestionProduct("דובדבן", "ירקות ופירות"),
            new SuggestionProduct("אפרסק", "ירקות ופירות"),
            new SuggestionProduct("שזיף", "ירקות ופירות"),
            new SuggestionProduct("אגס", "ירקות ופירות"),
            new SuggestionProduct("תמר", "ירקות ופירות"),
            new SuggestionProduct("רימון", "ירקות ופירות"),
            new SuggestionProduct("קלמנטינה", "ירקות ופירות"),
            new SuggestionProduct("תפוז", "ירקות ופירות"),
            new SuggestionProduct("אשכולית", "ירקות ופירות"),
            new SuggestionProduct("פטריות", "ירקות ופירות"),
            new SuggestionProduct("תירס", "ירקות ופירות"),
            new SuggestionProduct("אפונה", "ירקות ופירות"),
            new SuggestionProduct("שעועית ירוקה", "ירקות ופירות"),
            new SuggestionProduct("צנון", "ירקות ופירות"),
            new SuggestionProduct("כרישה", "ירקות ופירות"),
            new SuggestionProduct("סלרי", "ירקות ופירות"),
            new SuggestionProduct("קולורבי", "ירקות ופירות"),

            // ── מוצרי חלב ──
            new SuggestionProduct("חלב 3% תנובה 1 ליטר", "מוצרי חלב"),
            new SuggestionProduct("חלב 3% תנובה 2 ליטר", "מוצרי חלב"),
            new SuggestionProduct("חלב 1% תנובה", "מוצרי חלב"),
            new SuggestionProduct("חלב עיזים", "מוצרי חלב"),
            new SuggestionProduct("חלב ללא לקטוז", "מוצרי חלב"),
            new SuggestionProduct("שמנת לבישול 15%", "מוצרי חלב"),
            new SuggestionProduct("שמנת חמוצה 15%", "מוצרי חלב"),
            new SuggestionProduct("שמנת מתוקה 38%", "מוצרי חלב"),
            new SuggestionProduct("יוגורט טבעי תנובה", "מוצרי חלב"),
            new SuggestionProduct("יוגורט פירות", "מוצרי חלב"),
            new SuggestionProduct("יוגורט יווני", "מוצרי חלב"),
            new SuggestionProduct("לבן 1%", "מוצרי חלב"),
            new SuggestionProduct("לבן 3%", "מוצרי חלב"),
            new SuggestionProduct("גבינה צהובה 28%", "מוצרי חלב"),
            new SuggestionProduct("גבינה צהובה פרוסות", "מוצרי חלב"),
            new SuggestionProduct("גבינה בולגרית 5%", "מוצרי חלב"),
            new SuggestionProduct("גבינה לבנה 5%", "מוצרי חלב"),
            new SuggestionProduct("גבינה לבנה 9%", "מוצרי חלב"),
            new SuggestionProduct("קוטג' 5% תנובה", "מוצרי חלב"),
            new SuggestionProduct("קוטג' 9%", "מוצרי חלב"),
            new SuggestionProduct("ריקוטה", "מוצרי חלב"),
            new SuggestionProduct("מוצרלה", "מוצרי חלב"),
            new SuggestionProduct("גבינת פטה", "מוצרי חלב"),
            new SuggestionProduct("גבינת גאודה", "מוצרי חלב"),
            new SuggestionProduct("גבינת אמנטל", "מוצרי חלב"),
            new SuggestionProduct("חמאה 82%", "מוצרי חלב"),
            new SuggestionProduct("מרגרינה", "מוצרי חלב"),
            new SuggestionProduct("ביצים L 12 יחידות", "מוצרי חלב"),
            new SuggestionProduct("ביצים M 12 יחידות", "מוצרי חלב"),
            new SuggestionProduct("ביצים חופש", "מוצרי חלב"),
            new SuggestionProduct("פודינג שוקולד", "מוצרי חלב"),
            new SuggestionProduct("אשל 1.5%", "מוצרי חלב"),
            new SuggestionProduct("דנונה", "מוצרי חלב"),
            new SuggestionProduct("מילקי", "מוצרי חלב"),

            // ── בשר ודגים ──
            new SuggestionProduct("חזה עוף טרי", "בשר ודגים"),
            new SuggestionProduct("שוקיים עוף", "בשר ודגים"),
            new SuggestionProduct("כרעיים עוף", "בשר ודגים"),
            new SuggestionProduct("עוף שלם", "בשר ודגים"),
            new SuggestionProduct("כנפיים עוף", "בשר ודגים"),
            new SuggestionProduct("פרגית טחונה", "בשר ודגים"),
            new SuggestionProduct("בשר בקר טחון", "בשר ודגים"),
            new SuggestionProduct("אנטריקוט בקר", "בשר ודגים"),
            new SuggestionProduct("שניצל עוף", "בשר ודגים"),
            new SuggestionProduct("נקניקיות עוף", "בשר ודגים"),
            new SuggestionProduct("סלמון טרי פילה", "בשר ודגים"),
            new SuggestionProduct("דג ים טרי", "בשר ודגים"),
            new SuggestionProduct("טונה בשמן 160 גרם", "בשר ודגים"),
            new SuggestionProduct("טונה במים", "בשר ודגים"),
            new SuggestionProduct("סרדינים", "בשר ודגים"),
            new SuggestionProduct("שרימפס קפוא", "בשר ודגים"),
            new SuggestionProduct("קלמארי", "בשר ודגים"),
            new SuggestionProduct("המבורגר בקר", "בשר ודגים"),
            new SuggestionProduct("קציצות עוף", "בשר ודגים"),
            new SuggestionProduct("כבד עוף", "בשר ודגים"),

            // ── לחם ומאפים ──
            new SuggestionProduct("לחם לבן פרוס", "לחם ומאפים"),
            new SuggestionProduct("לחם מלא פרוס", "לחם ומאפים"),
            new SuggestionProduct("לחם שיפון", "לחם ומאפים"),
            new SuggestionProduct("לחם כוסמין", "לחם ומאפים"),
            new SuggestionProduct("לחמניות", "לחם ומאפים"),
            new SuggestionProduct("פיתה", "לחם ומאפים"),
            new SuggestionProduct("לאפה", "לחם ומאפים"),
            new SuggestionProduct("טורטייה", "לחם ומאפים"),
            new SuggestionProduct("קרואסון", "לחם ומאפים"),
            new SuggestionProduct("בייגל", "לחם ומאפים"),
            new SuggestionProduct("צ'יאבטה", "לחם ומאפים"),
            new SuggestionProduct("פוקאצ'ה", "לחם ומאפים"),
            new SuggestionProduct("עוגיות אורה", "לחם ומאפים"),
            new SuggestionProduct("עוגיות שוקולד", "לחם ומאפים"),
            new SuggestionProduct("קרקרים", "לחם ומאפים"),
            new SuggestionProduct("מצות", "לחם ומאפים"),
            new SuggestionProduct("רסק לחם", "לחם ומאפים"),
            new SuggestionProduct("לחם ללא גלוטן", "לחם ומאפים"),

            // ── שימורים וחטיפים ──
            new SuggestionProduct("שימורי עגבניות קצוצות", "שימורים וחטיפים"),
            new SuggestionProduct("רסק עגבניות", "שימורים וחטיפים"),
            new SuggestionProduct("שימורי תירס", "שימורים וחטיפים"),
            new SuggestionProduct("שימורי אפונה", "שימורים וחטיפים"),
            new SuggestionProduct("שימורי שעועית לבנה", "שימורים וחטיפים"),
            new SuggestionProduct("שימורי גרגרי חומוס", "שימורים וחטיפים"),
            new SuggestionProduct("שימורי עדשים", "שימורים וחטיפים"),
            new SuggestionProduct("זיתים שחורים", "שימורים וחטיפים"),
            new SuggestionProduct("זיתים ירוקים", "שימורים וחטיפים"),
            new SuggestionProduct("קטשופ", "שימורים וחטיפים"),
            new SuggestionProduct("מיונז", "שימורים וחטיפים"),
            new SuggestionProduct("חרדל", "שימורים וחטיפים"),
            new SuggestionProduct("רוטב סויה", "שימורים וחטיפים"),
            new SuggestionProduct("רוטב צ'ילי", "שימורים וחטיפים"),
            new SuggestionProduct("טחינה גולמית", "שימורים וחטיפים"),
            new SuggestionProduct("חמוצים", "שימורים וחטיפים"),
            new SuggestionProduct("ריבת תות", "שימורים וחטיפים"),
            new SuggestionProduct("ריבת תפוחים", "שימורים וחטיפים"),
            new SuggestionProduct("נוטלה 400 גרם", "שימורים וחטיפים"),
            new SuggestionProduct("חמאת בוטנים", "שימורים וחטיפים"),
            new SuggestionProduct("דבש טבעי", "שימורים וחטיפים"),
            new SuggestionProduct("ממרח שוקולד", "שימורים וחטיפים"),
            new SuggestionProduct("צ'יפס במבה", "שימורים וחטיפים"),
            new SuggestionProduct("ביסלי גריל", "שימורים וחטיפים"),
            new SuggestionProduct("ביסלי פיצה", "שימורים וחטיפים"),
            new SuggestionProduct("פרינגלס", "שימורים וחטיפים"),
            new SuggestionProduct("אגוזי מלך", "שימורים וחטיפים"),
            new SuggestionProduct("שקדים", "שימורים וחטיפים"),
            new SuggestionProduct("בוטנים קלויים", "שימורים וחטיפים"),
            new SuggestionProduct("גרעיני חמניות", "שימורים וחטיפים"),
            new SuggestionProduct("שוקולד מריר 70%", "שימורים וחטיפים"),
            new SuggestionProduct("שוקולד חלב", "שימורים וחטיפים"),
            new SuggestionProduct("שוקולד לבן", "שימורים וחטיפים"),
            new SuggestionProduct("ממתקי גומי", "שימורים וחטיפים"),
            new SuggestionProduct("פצפוצי אורז", "שימורים וחטיפים"),
            new SuggestionProduct("קורנפלקס", "שימורים וחטיפים"),
            new SuggestionProduct("גרנולה", "שימורים וחטיפים"),
            new SuggestionProduct("שיבולת שועל", "שימורים וחטיפים"),

            // ── קמח, אורז, קטניות ──
            new SuggestionProduct("קמח לבן 1 ק\"ג", "שימורים וחטיפים"),
            new SuggestionProduct("קמח מלא", "שימורים וחטיפים"),
            new SuggestionProduct("אורז לבן", "שימורים וחטיפים"),
            new SuggestionProduct("אורז מלא", "שימורים וחטיפים"),
            new SuggestionProduct("אורז בסמטי", "שימורים וחטיפים"),
            new SuggestionProduct("פסטה ספגטי", "שימורים וחטיפים"),
            new SuggestionProduct("פסטה פנה", "שימורים וחטיפים"),
            new SuggestionProduct("פסטה פרפרים", "שימורים וחטיפים"),
            new SuggestionProduct("אטריות ביצה", "שימורים וחטיפים"),
            new SuggestionProduct("קינואה", "שימורים וחטיפים"),
            new SuggestionProduct("כוסמת", "שימורים וחטיפים"),
            new SuggestionProduct("עדשים כתומות", "שימורים וחטיפים"),
            new SuggestionProduct("עדשים שחורות", "שימורים וחטיפים"),
            new SuggestionProduct("שעועית שחורה", "שימורים וחטיפים"),
            new SuggestionProduct("גרגרי חומוס יבש", "שימורים וחטיפים"),
            new SuggestionProduct("סוכר לבן", "שימורים וחטיפים"),
            new SuggestionProduct("סוכר חום", "שימורים וחטיפים"),
            new SuggestionProduct("מלח", "שימורים וחטיפים"),
            new SuggestionProduct("פלפל שחור טחון", "שימורים וחטיפים"),
            new SuggestionProduct("כמון", "שימורים וחטיפים"),
            new SuggestionProduct("פפריקה", "שימורים וחטיפים"),
            new SuggestionProduct("כורכום", "שימורים וחטיפים"),
            new SuggestionProduct("קינמון", "שימורים וחטיפים"),

            // ── משקאות ──
            new SuggestionProduct("קוקה קולה 500 מל", "משקאות"),
            new SuggestionProduct("קוקה קולה 1.5 ליטר", "משקאות"),
            new SuggestionProduct("קוקה קולה זירו", "משקאות"),
            new SuggestionProduct("ספרייט 500 מל", "משקאות"),
            new SuggestionProduct("ספרייט 1.5 ליטר", "משקאות"),
            new SuggestionProduct("פנטה תפוז", "משקאות"),
            new SuggestionProduct("מים מינרלים 500 מל", "משקאות"),
            new SuggestionProduct("מים מינרלים 1.5 ליטר", "משקאות"),
            new SuggestionProduct("מים מינרלים 6 בקבוקים", "משקאות"),
            new SuggestionProduct("מיץ תפוזים טבעי", "משקאות"),
            new SuggestionProduct("מיץ תפוחים", "משקאות"),
            new SuggestionProduct("מיץ ענבים", "משקאות"),
            new SuggestionProduct("מיץ אשכולית", "משקאות"),
            new SuggestionProduct("לימונדה", "משקאות"),
            new SuggestionProduct("חלב שוקולד", "משקאות"),
            new SuggestionProduct("בירה גולדסטאר 500 מל", "משקאות"),
            new SuggestionProduct("בירה נכון 330 מל", "משקאות"),
            new SuggestionProduct("יין אדום", "משקאות"),
            new SuggestionProduct("יין לבן", "משקאות"),
            new SuggestionProduct("קפה נס קלאסי 200 גרם", "משקאות"),
            new SuggestionProduct("קפה טורקי 500 גרם", "משקאות"),
            new SuggestionProduct("קפסולות נספרסו", "משקאות"),
            new SuggestionProduct("תה ירוק", "משקאות"),
            new SuggestionProduct("תה שחור", "משקאות"),
            new SuggestionProduct("תה נענע", "משקאות"),
            new SuggestionProduct("שוקו אבקה", "משקאות"),
            new SuggestionProduct("מי סודה", "משקאות"),
            new SuggestionProduct("איזוטוניק גטורייד", "משקאות"),
            new SuggestionProduct("בריסק לימון", "משקאות"),
            new SuggestionProduct("נקטר מנגו", "משקאות"),

            // ── ניקיון והיגיינה ──
            new SuggestionProduct("נייר טואלט 32 גלילים", "ניקיון והיגיינה"),
            new SuggestionProduct("מגבות נייר", "ניקיון והיגיינה"),
            new SuggestionProduct("מפיות נייר", "ניקיון והיגיינה"),
            new SuggestionProduct("שקיות אשפה גדולות", "ניקיון והיגיינה"),
            new SuggestionProduct("שקיות אשפה קטנות", "ניקיון והיגיינה"),
            new SuggestionProduct("נוזל כלים 750 מל", "ניקיון והיגיינה"),
            new SuggestionProduct("אבקת כביסה", "ניקיון והיגיינה"),
            new SuggestionProduct("נוזל כביסה", "ניקיון והיגיינה"),
            new SuggestionProduct("מרכך כביסה", "ניקיון והיגיינה"),
            new SuggestionProduct("סבון ידיים", "ניקיון והיגיינה"),
            new SuggestionProduct("אקונומיקה", "ניקיון והיגיינה"),
            new SuggestionProduct("ספוגים לכלים", "ניקיון והיגיינה"),
            new SuggestionProduct("מטלית ניקוי", "ניקיון והיגיינה"),
            new SuggestionProduct("נוזל ניקוי רצפות", "ניקיון והיגיינה"),
            new SuggestionProduct("שמפו", "ניקיון והיגיינה"),
            new SuggestionProduct("מרכך שיער", "ניקיון והיגיינה"),
            new SuggestionProduct("ג'ל רחצה", "ניקיון והיגיינה"),
            new SuggestionProduct("סבון גוף", "ניקיון והיגיינה"),
            new SuggestionProduct("קרם לחות פנים", "ניקיון והיגיינה"),
            new SuggestionProduct("קרם גוף", "ניקיון והיגיינה"),
            new SuggestionProduct("דאודורנט", "ניקיון והיגיינה"),
            new SuggestionProduct("משחת שיניים", "ניקיון והיגיינה"),
            new SuggestionProduct("מברשת שיניים", "ניקיון והיגיינה"),
            new SuggestionProduct("חוט דנטלי", "ניקיון והיגיינה"),
            new SuggestionProduct("תחבושות היגייניות", "ניקיון והיגיינה"),
            new SuggestionProduct("טמפונים", "ניקיון והיגיינה"),
            new SuggestionProduct("חיתולים", "ניקיון והיגיינה"),
            new SuggestionProduct("מגבונים לחים", "ניקיון והיגיינה"),
            new SuggestionProduct("ניקוי אסלה", "ניקיון והיגיינה"),
            new SuggestionProduct("ספריי חלונות", "ניקיון והיגיינה"),

            // ── שמנים ואפייה ──
            new SuggestionProduct("שמן זית כתית", "שימורים וחטיפים"),
            new SuggestionProduct("שמן קנולה 1 ליטר", "שימורים וחטיפים"),
            new SuggestionProduct("שמן חמניות", "שימורים וחטיפים"),
            new SuggestionProduct("חומץ תפוחים", "שימורים וחטיפים"),
            new SuggestionProduct("חומץ בלסמי", "שימורים וחטיפים"),
            new SuggestionProduct("אבקת אפייה", "שימורים וחטיפים"),
            new SuggestionProduct("שמרים יבשים", "שימורים וחטיפים"),
            new SuggestionProduct("סודה לשתייה", "שימורים וחטיפים"),
            new SuggestionProduct("וניל", "שימורים וחטיפים"),
            new SuggestionProduct("קקאו אבקה", "שימורים וחטיפים"),

            // ── קפוא ──
            new SuggestionProduct("ירקות מוקפאים מעורבים", "שימורים וחטיפים"),
            new SuggestionProduct("תירס מוקפא", "שימורים וחטיפים"),
            new SuggestionProduct("אפונה מוקפאת", "שימורים וחטיפים"),
            new SuggestionProduct("שניצל קפוא", "בשר ודגים"),
            new SuggestionProduct("פיצה קפואה", "שימורים וחטיפים"),
            new SuggestionProduct("גלידת וניל", "שימורים וחטיפים"),
            new SuggestionProduct("גלידת שוקולד", "שימורים וחטיפים"),
            new SuggestionProduct("ארטיק", "שימורים וחטיפים"),
            new SuggestionProduct("בורגר קפוא", "בשר ודגים"),
            new SuggestionProduct("פיש אנד צ'יפס", "בשר ודגים")
    );
}